import random

# mlecni_proizvodi        = ["Mleko", "Jogurt", "Sir", "Kajmak","Jogurt sa voćem", "Jogurt sa žitaricama", "Jaja", "Koziji sir", "Kozije mleko", "Mrvljeni sir"]
mlecni_proizvodi        = ["Mleko:2", "Jogurt:2", "Sir:3", "Kajmak:3", "Jogurt sa voćem:2", "Jogurt sa žitaricama:2", "Jaja:1", "Koziji sir:3", "Kozije mleko:2", "Mrvljeni sir:3"]
# voce_i_povrce           = ["Jabuke", "Kruške", "Višnje", "Trešnje", "Šljive","Maline","Jagode","Dunje","Breskve","Nektarine","Limun","Narandže","Limeta","Kajsije","Grožđe","Smokve","Borovnice","Ribizle","Kupine"]
voce_i_povrce           = ["Jabuke:3", "Kruške:3", "Višnje:3", "Trešnje:3", "Šljive:3", "Maline:3", "Jagode:3", "Dunje:3", "Breskve:3", "Nektarine:3", "Limun:3", "Narandže:3", "Limeta:3", "Kajsije:3", "Grožđe:3", "Smokve:3", "Borovnice:3", "Ribizle:3", "Kupine:3"]
# mesne_preradjevine      = ["Kulen","Kobasice","Svinjska jetra","Pileća jetra","Suvo meso","Šunka","Slanina","Mleveno svinjsko meso","Pileći narezak","Pileća paštete","Pileća kobasica","Pileći rolat","Goveđi narezak","Kobasice sa sirom","Domaća kobasica","Domaći kulen","Domaće slaninica","Domaći čvarci","Domaći suvi vrat","Domaći svinjski file","Domaća panceta","Domaća suva šunka","Domaće svinjske rebarca","Domaći dimljeni vrat","Svinjska mast","Slanina","Pileće viršle","Pileće viršle"]
mesne_preradjevine      = ["Kulen:3", "Kobasice:3", "Svinjska jetra:3", "Pileća jetra:3", "Suvo meso:3", "Šunka:3", "Slanina:3", "Mleveno svinjsko meso:3", "Pileći narezak:3", "Pileća pašteta:3", "Pileća kobasica:3", "Pileći rolat:3", "Goveđi narezak:3", "Kobasice sa sirom:3", "Domaća kobasica:3", "Domaći kulen:3", "Domaće slaninica:3", "Domaći čvarci:3", "Domaći suvi vrat:3", "Domaći svinjski file:3", "Domaća panceta:3", "Domaća suva šunka:3", "Domaće svinjske rebarca:3", "Domaći dimljeni vrat:3", "Svinjska mast:3", "Slanina:3", "Pileće viršle:3", "Pileće viršle:3"]
# sveze_meso              = ["Svinjsko meso","Junetina","Pileće meso","Jagnjeće meso","Teletina","Piletina bez kože","Pileće belo meso","Svinjski but","Svinjski vrat","Svinjski bataci","Svinjska rebra","Junetina bez kostiju","Teleće šnicle","Pileći bataci","Pileća krilca","Pileći filet","Junetina sa kostima","Svinjska kolenica","Svinjski kare","Junetina za gulaš","Junetina za roštilj","Pileći ražnjići","Jagnjeća plećka","Teletina za šniclu","Pileći karabatak","Svinjska plećka"]
sveze_meso              = ["Svinjsko meso:3", "Junetina:3", "Pileće meso:3", "Jagnjeće meso:3", "Teletina:3", "Piletina bez kože:3", "Pileće belo meso:3", "Svinjski but:3", "Svinjski vrat:3", "Svinjski bataci:3", "Svinjska rebra:3", "Junetina bez kostiju:3", "Teleće šnicle:3", "Pileći bataci:3", "Pileća krilca:3", "Pileći filet:3", "Junetina sa kostima:3", "Svinjska kolenica:3", "Svinjski kare:3", "Junetina za gulaš:3", "Junetina za roštilj:3", "Pileći ražnjići:3", "Jagnjeća plećka:3", "Teletina za šniclu:3", "Pileći karabatak:3", "Svinjska plećka:3"]
# zitarice                = ["Pšenica","Raž","Ječam","Ovas","Kukuruz","Pirinač","Proso","Heljda","Jabučni ovas","Kinoa","Amarant","Ječmena krupica","Ovsene pahulje","Integralni pirinač","Pšenični griz","Brašno od pira","Brašno od heljde","Brašno od kukuruza","Integralni hleb","Pahuljice od pira","Musli","Pšenične klice","Integralne testenine","Pirinač u kori","Ovseni hleb","Raženi hleb","Ječmeni hleb","Integralni krekeri","Integralni keks"]
zitarice                = ["Pšenica:3", "Raž:3", "Ječam:3", "Ovas:3", "Kukuruz:3", "Pirinač:3", "Proso:3", "Heljda:3", "Jabučni ovas:3", "Kinoa:3", "Amarant:3", "Ječmena krupica:3", "Ovsene pahulje:3", "Integralni pirinač:3", "Pšenični griz:3", "Brašno od pira:3", "Brašno od heljde:3", "Brašno od kukuruza:3", "Integralni hleb:3", "Pahuljice od pira:3", "Musli:3", "Pšenične klice:3", "Integralne testenine:3", "Pirinač u kori:3", "Ovseni hleb:3", "Raženi hleb:3", "Ječmeni hleb:3", "Integralni krekeri:3", "Integralni keks:3"]
# napici                  = ["Breskva-kajsija kompot","Jabuka-šljiva kompot","Trešnja-višnja kompot","Kruška-jabuka kompot","Dunja kompot","Rakija","Domaći likeri","Vino","Sirupi od raznog voća","Kiseli kupusov sok","Domaći kefir","Domaći jogurt","Kisela voda","Sok od paradajza","Sok od jabuka","Sok od višanja","Sok od malina","Sok od kupina","Sok od breskve","Sok od kruške","Sok od šljive","Domaći čajevi","Napitci sa začinima","Domaći voćni čaj","Domaći napitak od nane","Domaći limunada","Domaći ledolomac","Domaći smoothie","Domaći voćni likeri","Domaći hladni čajevi"]
napici                  = ["Breskva-kajsija kompot:2", "Jabuka-šljiva kompot:2", "Trešnja-višnja kompot:2", "Kruška-jabuka kompot:2", "Dunja kompot:2", "Rakija od maline:2", "Domaći likeri:2", "Vino:2", "Sirupi od raznog voća:2", "Kiseli kupusov sok:2", "Domaći kefir:2", "Domaći jogurt:2", "Kisela voda:2", "Sok od paradajza:2", "Sok od jabuka:2", "Sok od višanja:2", "Sok od malina:2", "Sok od kupina:2","Sok od breskve:2", "Sok od kruške:2", "Sok od šljive:2", "Domaći čajevi:2", "Napitci sa začinima:2", "Domaći voćni čaj:2", "Domaći napitak od nane:2", "Domaći limunada:2", "Domaći ledolomac:2", "Domaći smoothie:2", "Domaći voćni likeri:2", "Domaći hladni čajevi:2"]
# biljna_ulja             = ["Suncokretovo ulje","Ulje od repice","Maslinovo ulje","Ulje od lanenog semena","Kukuruzno ulje","Ulje od susama","Ulje od bundevinih semenki","Ulje od koštica grožđa","Ulje od oraha","Ulje od badema","Ulje od avokada","Ulje od kokosa","Ulje crnog kima","Ulje od argana","Ulje od konoplje","Ulje od soje","Ulje od uljane repice","Ulje od makadamije","Ulje od orhideje","Ulje od nara","Ulje od divlje ruže"]
biljna_ulja             = ["Suncokretovo ulje:2", "Ulje od repice:2", "Maslinovo ulje:2", "Ulje od lanenog semena:2", "Kukuruzno ulje:2", "Ulje od susama:2", "Ulje od bundevinih semenki:2", "Ulje od koštica grožđa:2", "Ulje od oraha:2", "Ulje od badema:2", "Ulje od avokada:2", "Ulje od kokosa:2", "Ulje crnog kima:2", "Ulje od argana:2", "Ulje od konoplje:2", "Ulje od soje:2", "Ulje od uljane repice:2", "Ulje od makadamije:2", "Ulje od orhideje:2", "Ulje od nara:2", "Ulje od divlje ruže:2"]
# namazi                  = ["Ajvar","Tahini","Livadski med","Bagremov med","Šumski med","Planinski med","Med od lavande","Med od maslačka","Med od divlje trešnje","Med od suncokretovog cveta","Med od lipe""Ljutenica","Pindžur","Urnebes","Namaz crnih maslina","Namaz belih maslina","Namaz paradajza","Maslac od kikirikija","Namaz bundeve","Namaz suvih paradajza","Hummus","Namaz susama i meda","Namaz pečuraka","Namaz od avokada","Namaz od paprike","Džem od voća","Namaz od jaja i majoneza","Namaz od tunjevine","Namaz od lososa","Namaz od hrena","Pesto sos","Namaz crvene paprike i oraha","Namaz od mladog luka","Namaz od sira i belog luka","Namaz mirođije i feta sira"]
namazi                  = ["Ajvar:1:500", "Tahini:1:500", "Livadski med:1:500", "Bagremov med:1:500", "Šumski med:1:500", "Planinski med:1:500", "Med od lavande:1:500", "Med od maslačka:1:500", "Med od divlje trešnje:1:500", "Med od suncokretovog cveta:1:500", "Med od lipe:1:500","Ljutenica:1:500", "Pindjur:1:500", "Urnebes:2", "Namaz crnih maslina:1:500", "Namaz belih maslina:1:500", "Namaz paradajza:1:500", "Maslac od kikirikija:2", "Namaz bundeve:1:500", "Namaz suvih paradajza:1:500", "Hummus:2", "Namaz susama i meda:1:500", "Namaz pečuraka:1:500", "Namaz od avokada:1:500", "Namaz od paprike:1:500", "Džem od voća:2", "Namaz od jaja i majoneza:1:500", "Namaz od tunjevine:1:500", "Namaz od lososa:1:500", "Namaz od hrena:1:500", "Pesto sos:1:500", "Namaz crvene paprike i oraha:1:500", "Namaz od mladog luka:1:500", "Namaz od sira i belog luka:1:500", "Namaz mirođije i feta sira:1:500"]

# category_producs_list   = [{"mlecni_proizvodi":mlecni_proizvodi}, {"voce_i_povrce":voce_i_povrce}, {"mesne_preradjevine":mesne_preradjevine}, {"sveze_meso":sveze_meso}, {"zitarice":zitarice}, {"napici":napici}, {"biljna_ulja":biljna_ulja}, {"namazi_skraceni":namazi_skraceni}]
category_producs_list   = [{1:mlecni_proizvodi}, {2:voce_i_povrce}, {3:mesne_preradjevine}, {3:sveze_meso}, {5:zitarice}, {6:napici}, {7:biljna_ulja}, {8:namazi}]

floor_price             = [200, 150, 1000, 1000, 150, 210, 270, 250]
ceiling_price           = [700, 400, 2300, 2300, 500, 400, 600, 700]

list_of_comments        = ["Izvanredan ukus, prava domaća poslastica!","Oduševljena svakim zalogajem! ","Autentično i ukusno, pravo otkriće.","Divno iznenađenje za nepce!","Domaće nikada nije bilo bolje.""Savršen spoj tradicije i kvaliteta.","Ukusno i domaće, pravo otkriće!","Sjajan proizvod, svaki zalogaj je uživanje","Autentičan ukus, prava poslastica","Oduševljena kvalitetom, preporučujem svima","Nikada nisam probao nešto tako dobro","Savršena kombinacija tradicije i vrhunskog kvaliteta","Savršeno domaće zadovoljstvo!","Toplo preporučujem, prava poslastica!","Ukus tradicije u svakom zalogaju!"]
list_of_description     = ["Otkrijte jedinstvenu harmoniju ukusa u svakom zalogaju ovog domaćeg proizvoda. Uživajte u spoju tradicije i kvaliteta.","Sa svakim grickalicom ovog proizvoda, putujete kroz vreme do domaće kuhinje puna mirisa i toplih uspomena.","Domaći proizvod koji nosi pečat tradicije, pružajući vam autentičan doživljaj ukusa iz najboljih lokalnih izvora.","Ovaj proizvod je više od hrane - to je priča o ljubavi prema domaćim specijalitetima, ispričana kroz jedinstveni ukus.","Ukusna sinergija tradicionalnih sastojaka čini ovaj proizvod posebnim dodatkom vašem stolu, donoseći toplinu i autentičnost.","Kroz svaki komad ovog proizvoda osećate se kao da ste u srcu domaće kuhinje. Opuštanje i uživanje u svakom trenutku.""Domaći proizvod koji je spoj nasleđa i inovacija, donoseći vam savršenu ravnotežu ukusa i tekstura.","Ovaj proizvod je mala doza doma u svakom pakovanju. Iskusite izvanredan spoj tradicije i savremene kulinarske veštine.","Svaki zalogaj ovog proizvoda je kao pozivnica na putovanje kroz domaće okuse. Jednostavno uživanje u najboljem.","Ukusno putovanje kroz lokalne proizvode, ovaj proizvod je priznanje dobrom ukusu i posvećenosti autentičnosti.","Autentičan ukus domaće tradicije upakovan u svaki zalogaj ovog proizvoda. Otkrijte pravu raskoš domaćih ukusa.","Savršeno spojene tradicije i kvaliteta, ovaj proizvod pruža nezaboravno gastronomsko iskustvo.","Domaći proizvod s ljubavlju spravljen, pruža vam istinski ukus i aromu lokalne kuhinje.","Ovaj proizvod je simbol domaćeg truda i stručnosti, donoseći vam nezaboravne trenutke uživanja u hrani.","Ukusna avantura koja oživljava domaću kuhinju. Isprobajte ovaj proizvod i pridružite se čarima tradicionalnih recepata.","Svestrani domaći proizvod koji će zadovoljiti vaše nepce i dodati notu autentičnosti vašim jelima.","Jedinstvena kombinacija tradicije i svežih sastojaka, ovaj proizvod je prava poslastica za ljubitelje domaće hrane.","Uživajte u bogatstvu ukusa domaće kuhinje uz ovaj izuzetan proizvod.","Kvalitet sastojaka i pažljiva proizvodnja čine ovaj proizvod pravim izborom za sve ljubitelje domaće hrane.","Ovaj proizvod je odraz ljubavi prema tradiciji i pruža pravo gurmansko iskustvo iz udobnosti vašeg doma."]

def getRandomProduct():
    random_category_index       = random.randrange(0,(len(category_producs_list))) 
    list_for_random_category    = next(iter(category_producs_list[random_category_index].values()))
    random_product_index        = random.randrange(0,(len(list_for_random_category)))

    random_category             = next(iter(category_producs_list[random_category_index].keys()))
    random_price                = generateRandomProductPrice(random_category)
    random_product              = category_producs_list[random_category_index][random_category][random_product_index]
    random_description          = list_of_description[random.randrange(0, len(list_of_description))]

    return random_category, random_product, random_description, random_price

def generateRandomProductPrice(categoryId):
    last_digit = [5, 9]
    price = random.randint(floor_price[categoryId - 1], ceiling_price[categoryId - 1]) // 10 * 10
    
    random_number = random.random()
    if(random_number < 0.4):
        price = price + random.choice(last_digit)
        
    return price

